### ISSUE TITLE
Error during online phase execution

### ISSUE THREAD

**Issue by yoopaan** [bit-ml/Private-Set-Intersection#2]
I followed the command on the readme to execute:

1. clone code and install requirements 

2. generate the datasets 

	python3 set_gen.py

3. offline preprocess

	python3 client_offline.py

	python3 server_offline.py

4. online phase 

client:

```

➜  Private-Set-Intersection git:(main) ✗ python3 client_online.py
Traceback (most recent call last):
  File "client_online.py", line 52, in <module>
    key_inverse = pow(oprf_client_key, -1, order_of_generator)
ValueError: pow() 2nd argument cannot be negative when 3rd argument specified

```

server:

```
➜  Private-Set-Intersection git:(main) ✗ python3 server_online.py
 * OPRF layer done!
Traceback (most recent call last):
  File "server_online.py", line 52, in <module>
    L = int(L, 10)
ValueError: invalid literal for int() with base 10: ''
```

![截屏2021-10-18 下午8 34 45](https://user-images.githubusercontent.com/38783332/137731520-30e6e29d-2097-4b05-883a-0f97516939b8.png)
![截屏2021-10-18 下午8 34 53](https://user-images.githubusercontent.com/38783332/137731529-254843e8-238f-4fb6-aca7-8d34e3c98595.png)

**Comment by Charles518** [comment]
I encountered same issues listed above.

**Comment by rtitiu** [comment]
The problem seems to be that the specific pow and int functions are not supported by your version of Python. Try using a newer version of Python (ex. 3.8.10 should work).

**Comment by yoopaan** [comment]
> The problem seems to be that the specific pow and int functions are not supported by your version of Python. Try using a newer version of Python (ex. 3.8.10 should work).

sloved.
thanks！
