### ISSUE TITLE
server_online.py is not giving any output

### ISSUE THREAD

**Issue by sachipatel27** [bit-ml/Private-Set-Intersection#4]
I has been hours since server_online.py is running on my ubuntu system but there is no progress whether it will give any output or not

**Comment by mbolboceanu** [comment]
Hello. Can you give more details on your error? What parameters (for e.g. server_size) have you considered?

**Comment by sachipatel27** [comment]
I have not understood what you meant by server size
cloned the repository and then installed all the requirements on ubuntu and
then ran following commands
python3 set_gen.py
python3 server_offline.py
python3 client_offline.py
python3 server_online.py
But after running the last command the code is taking hours and Still there
is no output
Can you please give me the instructions on what exactly I have to do to run
this repository

**Comment by mbolboceanu** [comment]
I thought you changed the size of the server, server_size, in parameters.py.
The order of running the files that you described is the right one :). I think you also need to run 
python3 client_online.py. 
after
python3 server_online.py
Does server_online.py give any output after running client_online.py?

**Comment by sachipatel27** [comment]
After running the command python3 server_online.py there is no response.
How much time does server_online.py take?

**Comment by mbolboceanu** [comment]
Did you also run client_online.py? server_online.py won't give any response, except when running also client_online.py. If you run both server_online.py and client_online.py (in this order), server_online.py should give an output in approx. 3 seconds.

**Comment by sachipatel27** [comment]
Okay I understood,  does the code also give any results or the data as an
output?

**Comment by mbolboceanu** [comment]
After running both server_online.py and client_online.py, the first file gives as output Server ONLINE computation time, whereas the second file gives as output if intersection is recovered correctly, the Client ONLINE computation time, the size of Server to Client communication and of Client to Server communication. Here is a sample of outputs you should see:
```
/home/mada/PycharmProjects/Private-Set-Intersection/venv/bin/python /home/mada/PycharmProjects/Private-Set-Intersection/server_online.py
 * OPRF layer done!
Client disconnected 

Server ONLINE computation time 9.19s

Process finished with exit code 0
```
```
/home/mada/PycharmProjects/Private-Set-Intersection/venv/bin/python /home/mada/PycharmProjects/Private-Set-Intersection/client_online.py
 * OPRF protocol done!
 * Sending the context and ciphertext to the server....
 * Waiting for the servers's answer...

 Intersection recovered correctly: True
Disconnecting...

  Client ONLINE computation time 7.08s
  Communication size:
    ~ Client --> Server:  6.10 MB
    ~ Server --> Client:  6.82 MB

Process finished with exit code 0
```

**Comment by sachipatel27** [comment]
Understood, Thanks a lot. :)
