### ISSUE TITLE
Is there a way to optimize the cuckoo hashing

### ISSUE THREAD

**Issue by sachipatel27** [bit-ml/Private-Set-Intersection#6]
can we optimize the cuckoo hashing of the above code. If yes then kindly elaborate

**Comment by mbolboceanu** [comment]
We implemented Cuckoo hashing as explained in Section 4.2 here: https://eprint.iacr.org/2017/299.pdf. Maybe there are coding optimizations, but we are not aware of them. You can also check this library Microsoft implemented in C++ for Cuckoo hashing: https://github.com/Microsoft/Kuku
